language: c++
compiler: gcc
sudo: true
matrix:
  include:
  # fully specify builds, include can't dynamically expand matrix entries
  # relative order of sudo and env is important so that addons: is recognized

  - os: linux
    dist: trusty
    sudo: required
    env: TARGET="linux"
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-4.9
          - g++-4.9
    - os: osx
      compiler: clang
      env: TARGET="osx"
    - os: osx
      compiler: clang
      env: TARGET="ios"

  exclude:
    - compiler: gcc

install:
  - if [ "$TARGET" == "android" ] || [ "$TARGET" == "linux" ] || [ "$TARGET" == "linuxarmv6" ] || [ "$TARGET" == "linuxarmv7" ] || [ "$TARGET" == "docs" ] || [ "$TARGET" == "osx" ] || [ "$TARGET" == "emscripten" ]; then
        scripts/ci/$TARGET/install.sh;
    fi

script:
  - scripts/ci/$TARGET/build.sh $OPT
  - if [ "$TARGET" == "osx" ] || [ "$TARGET" == "linux" ]; then
      scripts/ci/$TARGET/run_tests.sh;
    fi

git:
  depth: 10
